import { ConstructionSiteRepository } from "../modules/constructionSite/repository/ConstructionSiteRepository";
import { IConstructionSiteRepository } from "../modules/constructionSite/repository/IConstructionSiteRepository";
import { ConstructionSiteService } from "../modules/constructionSite/service/ConstructionSiteService";
import { IConstructionSiteService } from "../modules/constructionSite/service/IConstructionSiteService";
import { EquipmentHourRepository } from "../modules/equipment/repository/EquipmentHourRepository";
import { EquipmentRepository } from "../modules/equipment/repository/EquipmentRepository";
import { IEquipmentHourRepository } from "../modules/equipment/repository/IEquipmentHourRepository";
import { IEquipmentRepository } from "../modules/equipment/repository/IEquipmentRepository";
import { EquipmentService } from "../modules/equipment/service/EquipmentService";
import { IEquipmentService } from "../modules/equipment/service/IEquipmentService";
import { ILubricationSheetRepository } from "../modules/lubricationSheet/repository/ILubricationSheetRepository";
import { ILubricationSheetSparePartRepository } from "../modules/lubricationSheet/repository/ILubricationSheetSparePartRepository";
import { LubricationSheetRepository } from "../modules/lubricationSheet/repository/LubricationSheetRepository";
import { LubricationSheetSparePartRepository } from "../modules/lubricationSheet/repository/LubricationSheetSparePartRepository";
import { ILubricationSheetService } from "../modules/lubricationSheet/service/ILubricationSheetService";
import { LubricationSheetService } from "../modules/lubricationSheet/service/LubricationSheetService";
import { IMaintenanceFrequencyRepository } from "../modules/maintenance/repository/IMaintenanceFrequecyRepository";
import { IMaintenanceRepository } from "../modules/maintenance/repository/IMaintenanceRepository";
import { IMaintenanceSparePartRepository } from "../modules/maintenance/repository/IMaintenanceSparePartRepository";
import { INextMaintenanceRepository } from "../modules/maintenance/repository/INextMaintenanceRepository";
import { MaintenanceFrequencyRepository } from "../modules/maintenance/repository/MaintenanceFrequencyRepository";
import { MaintenanceRepository } from "../modules/maintenance/repository/MaintenanceRepository";
import { MaintenanceSparePartRepository } from "../modules/maintenance/repository/MaintenanceSparePartRepository";
import { NextMaintenanceRepository } from "../modules/maintenance/repository/NextMaintenanceRepository";
import { IMaintenanceService } from "../modules/maintenance/service/IMaintenanceService";
import { IMaintenanceSparePartService } from "../modules/maintenance/service/IMaintenanceSparePartService";
import { INextMaintenanceService } from "../modules/maintenance/service/INextMaintenanceService";
import { MaintenanceService } from "../modules/maintenance/service/MaintenanceService";
import { MaintenanceSparePartService } from "../modules/maintenance/service/MaintenanceSparePartService";
import { NextMaintenanceService } from "../modules/maintenance/service/NextMaintenanceService";
import { ISparePartRepository } from "../modules/sparePart/repository/ISparePartRepository";
import { SparePartRepository } from "../modules/sparePart/repository/SparePartRepository";
import { ISparePartService } from "../modules/sparePart/service/ISparePartService";
import { SparePartService } from "../modules/sparePart/service/SparePartService";
import { IUserRepository } from "../modules/user/repository/IUserRepository";
import { UserRepository } from "../modules/user/repository/UserRepository";
import { IUserService } from "../modules/user/service/IUserService";
import { UserService } from "../modules/user/service/UserService";
import { container } from "tsyringe";

// Repositories
container.registerSingleton<IConstructionSiteRepository> (ConstructionSiteRepository);
container.registerSingleton<IEquipmentRepository> (EquipmentRepository);
container.registerSingleton<IEquipmentHourRepository> (EquipmentHourRepository);
container.registerSingleton<ILubricationSheetRepository> (LubricationSheetRepository);
container.registerSingleton<ILubricationSheetSparePartRepository> (LubricationSheetSparePartRepository);
container.registerSingleton<IMaintenanceRepository> (MaintenanceRepository);
container.registerSingleton<IMaintenanceFrequencyRepository> (MaintenanceFrequencyRepository);
container.registerSingleton<IMaintenanceSparePartRepository> (MaintenanceSparePartRepository);
container.registerSingleton<INextMaintenanceRepository> (NextMaintenanceRepository);
container.registerSingleton<ISparePartRepository> (SparePartRepository);
container.registerSingleton<IUserRepository> (UserRepository);

// Services
container.registerSingleton<IConstructionSiteService> (ConstructionSiteService);
container.registerSingleton<IEquipmentService> (EquipmentService);
container.registerSingleton<ILubricationSheetService> (LubricationSheetService);
container.registerSingleton<IMaintenanceService> (MaintenanceService);
container.registerSingleton<IMaintenanceSparePartService> (MaintenanceSparePartService);
container.registerSingleton<INextMaintenanceService> (NextMaintenanceService);
container.registerSingleton<ISparePartService> (SparePartService);
container.registerSingleton<IUserService> (UserService);